### ISSUE TITLE
react-native-tcp-socket  error NativeModules.TcpSockets

### ISSUE THREAD

**Issue by vallemar** [OpenNative/open-native#9]
When I try to use the react-native-tcp-socket plugin I get an exception when making the connection:

```
System.err: An uncaught Exception occurred on "main" thread.
  System.err: Calling js method onClick failed
  System.err: TypeError: Cannot read property 'connect' of undefined
  System.err:
  System.err: StackTrace:
  System.err: connect(file: app\webpack:\app-ns-rn\node_modules\react-native-tcp-socket\src\Socket.js:168:16)
  System.err:   at createConnection(file: app\webpack:\app-ns-rn\node_modules\react-native-tcp-socket\src\index.js:50:21)
```

It seems that TcpSockets is undefined in this line: https://github.com/Rapsssito/react-native-tcp-socket/blob/master/src/Socket.js#L167 and this import comes from here https://github.com/Rapsssito/react-native-tcp-socket/blob/master/src/Socket.js#L6 and from `react-native`
